stages:
  - testing
  - docs

.test_template: &test_template
  stage: testing
  image: asteinh/ocpx-base
  tags:
    - docker
  cache:
    paths:
      - .pip
  before_script:
    - source activate ocpx
    - mkdir -p .pip
    - pip --cache-dir=.pip install casadi
    - export PYTHONPATH=$PYTHONPATH:$(pwd)

testing:unittests:
  <<: *test_template
  script:
    - nosetests
  # only:
  #   - master

testing:examples:
  <<: *test_template
  # before_script:
  #   - echo $PYTHONPATH
  script:
    - python examples/working/hello_world.py
  # only:
  #   - master
