stages:
  - testing

# testing:unit-tests:
#   stage: testing
#   image: conda/miniconda3-centos7
#   tags:
#     - meco
#   before_script:
#     - ...
#   script:
#     - ...
#   only:
#     - master

testing:examples:
  stage: testing
  image: asteinh/ocpx-base
  tags:
    - docker
  before_script:
    - source activate ocpx
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - echo $PYTHONPATH
  script:
    - python -v examples/working/hello_world.py
  # only:
  #   - master
