stages:
  - testing
  - docs
  - publish

# shorthand for testing
.test_template: &template
  image: asteinh/ocpx-base
  tags:
    - docker
  cache:
    paths:
      - .pip
  # only:
  #   - master

# preparation for all stages
before_script:
  - source activate ocpx
  - mkdir -p .pip
  - pip --cache-dir=.pip install casadi
  - pip --cache-dir=.pip install sphinx_rtd_theme
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

testing:unittests:
  stage: testing
  <<: *template
  script:
    - nosetests

testing:examples:
  stage: testing
  <<: *template
  script:
    - python examples/working/hello_world.py

docs:sphinx:
  stage: docs
  <<: *template
  dependencies:
    - testing:unittests
    - testing:examples
  script:
    - cd docs/sphinx && mkdir -p apidoc
    - sphinx-apidoc -f -o ./apidoc/ ../../ocpx/
    - make html
  artifacts:
    paths:
      - docs/sphinx/build

pages:
  stage: publish
  tags:
    - pages
  dependencies:
    - docs:sphinx
  script:
    - mkdir public
    - cp -R ./docs/sphinx/build/html/ ./public/
  artifacts:
    paths:
      - public
  # only:
  #   - master
